language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt --quiet
  - pip install black flake8 flake8-bugbear isort
script:
  - black --check .
  - flake8
  - isort **/*.py -c -vb
cache: pip
